#!/bin/bash

cleanup() {
 tvservice -o
 trap - INT TERM EXIT
}
trap cleanup INT TERM EXIT

tvservice -s | grep -q "is off"
disp=$?

host=${MPD_HOST:-localhost}

base=/tmp/mpd.status
export DISPLAY=:13
nohup X $DISPLAY > /dev/null 2>&1 < /dev/null &
until xset s off && xset -dpms && xset s noblank; do sleep 1; done

rm -f $base.{now,last}
touch $base.{now,last}
(echo start
 while true; do
  mpc idle
 done) |
while read -t10 || true; do
 while read -t0; do true; done
 (
 echo currentsong|netcat $host 6600|awk ' !x[$0]++'|sed -n 's/\.[A-Za-z0-9]\{3,4\}$//;s/^\(Album\|Artist\|Title\): //p'|tac
 echo
 echo currentsong|netcat $host 6600|grep -vE ': *[a-z]{3,4}$' |sed -n 's/Genre: //p'|tac
 ) |sed '10{s/$/ .../;q}' > $base.next
 cp $base{.next,.now}
 cmp -s $base.{now,last} || {
 cp $base.{now,last} &&
 cat $base.now &&
 echo --- &&
 DISPLAY=:13 gnome-osd-client -f "<message id=\"mpd\" osd_vposition=\"center\" osd_halignment=\"center\" osd_font=\"Helvetica 48\" hide_timeout=\"10000000000\" hide_on_hover=\"false\" animations=\"true\" drop_shadow=\"true\"><span color=\"white\">$(cat $base.now)</span></message>"
 }
 echo status|netcat $host 6600|grep ^state:|grep -vq play
 state=$?
 [ $disp -eq $state ] ||
 if [ $state -eq 0 ]; then
  tvservice -o
 else
  tvservice -p
  sudo chvt 8
  sudo chvt 7
 fi > /dev/null 2>&1
 disp=$state
done
