#!/bin/bash

disp=100
host=${MPD_HOST:-localhost}

base=/tmp/mpd.status
export DISPLAY=:13
nohup X $DISPLAY > /dev/null 2>&1 < /dev/null &
until xset s off && xset -dpms && xset s noblank; do sleep 1; done

rm -f $base.{now,last}
touch $base.{now,last}
while true; do
 (
 echo currentsong|netcat $host 6600|sed -n 's/\.[A-Za-z0-9]\{3,4\}$//;s/^\(Album\|Artist\|Title\): //p'|tac
 echo
 echo currentsong|netcat $host 6600|sed -n 's/Genre: //p'
 ) |sed '10{s/$/ .../;q}' > $base.next
 cp $base{.next,.now}
 echo start
 mpc idle
done |
while read -t5 && sleep 2 || true; do
 cmp -s $base.{now,last} || {
 cp $base.{now,last} &&
 cat $base.now &&
 echo --- &&
 DISPLAY=:13 gnome-osd-client -f "<message id=\"mpd\" osd_vposition=\"center\" osd_halignment=\"center\" osd_font=\"Helvetica 48\" hide_timeout=\"10000000000\" hide_on_hover=\"false\" animations=\"true\" drop_shadow=\"true\"><span color=\"white\">$(cat $base.now)</span></message>"
 }
 echo status|netcat $host 6600|grep ^state:|grep -vq play
 state=$?
 [ $disp -eq $state ] ||
 if [ $state -eq 0 ]; then
  tvservice -o
 else
  tvservice -p
  sudo chvt 8
  sudo chvt 7
 fi > /dev/null 2>&1
 disp=$state
done
